# Generated by Django 6.1 on 2026-09-02 18:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agency_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('agency_name', models.CharField(max_length=255)),
                ('agency_url', models.URLField(max_length=500)),
                ('agency_timezone', models.CharField(max_length=63)),
                ('agency_phone', models.CharField(blank=True, max_length=255)),
                ('agency_lang', models.CharField(blank=True, max_length=35)),
            ],
            options={
                'verbose_name_plural': 'agencies',
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('service_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('monday', models.BooleanField()),
                ('tuesday', models.BooleanField()),
                ('wednesday', models.BooleanField()),
                ('thursday', models.BooleanField()),
                ('friday', models.BooleanField()),
                ('saturday', models.BooleanField()),
                ('sunday', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ('service_id',),
            },
        ),
        migrations.CreateModel(
            name='FeedInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_publisher_name', models.CharField(max_length=255)),
                ('feed_publisher_url', models.URLField(max_length=500)),
                ('feed_lang', models.CharField(max_length=35)),
                ('feed_start_date', models.DateField(blank=True, null=True)),
                ('feed_end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'feed information',
                'verbose_name_plural': 'feed information',
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('stop_code', models.CharField(blank=True, max_length=255)),
                ('stop_name', models.CharField(max_length=255)),
                ('stop_lat', models.DecimalField(decimal_places=12, max_digits=15, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('stop_lon', models.DecimalField(decimal_places=12, max_digits=15, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('zone_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('stop_name', 'stop_code'),
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('route_short_name', models.CharField(blank=True, max_length=255)),
                ('route_long_name', models.CharField(blank=True, max_length=255)),
                ('route_desc', models.TextField(blank=True)),
                ('route_type', models.PositiveSmallIntegerField(choices=[(0, 'Tram, streetcar, or light rail'), (1, 'Subway or metro'), (2, 'Rail'), (3, 'Bus'), (4, 'Ferry'), (5, 'Cable tram'), (6, 'Aerial lift'), (7, 'Funicular'), (11, 'Trolleybus'), (12, 'Monorail')])),
                ('route_color', models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a six-character hexadecimal color without the leading #.', regex='^[0-9A-Fa-f]{6}$')])),
                ('route_text_color', models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a six-character hexadecimal color without the leading #.', regex='^[0-9A-Fa-f]{6}$')])),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='gtfs.agency')),
            ],
            options={
                'ordering': ('route_short_name', 'route_id'),
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.CharField(db_index=True, max_length=255)),
                ('shape_pt_lat', models.DecimalField(decimal_places=12, max_digits=15, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('shape_pt_lon', models.DecimalField(decimal_places=12, max_digits=15, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('shape_pt_sequence', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('shape_id', 'shape_pt_sequence'),
                'constraints': [models.UniqueConstraint(fields=('shape_id', 'shape_pt_sequence'), name='gtfs_unique_shape_point_sequence')],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('trip_headsign', models.CharField(blank=True, max_length=255)),
                ('direction_id', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Direction 0'), (1, 'Direction 1')], null=True)),
                ('shape_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('wheelchair_accessible', models.PositiveSmallIntegerField(choices=[(0, 'No accessibility information'), (1, 'Wheelchair accessible'), (2, 'Not wheelchair accessible')], default=0)),
                ('brigade', models.CharField(blank=True, max_length=255)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='gtfs.route')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='gtfs.calendar')),
            ],
            options={
                'ordering': ('route_id', 'trip_id'),
            },
        ),
        migrations.CreateModel(
            name='CalendarDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('exception_type', models.PositiveSmallIntegerField(choices=[(1, 'Service added'), (2, 'Service removed')])),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='gtfs.calendar')),
            ],
            options={
                'ordering': ('date', 'service_id'),
                'constraints': [models.UniqueConstraint(fields=('service', 'date'), name='gtfs_unique_service_exception_date')],
            },
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DurationField(blank=True, null=True)),
                ('departure_time', models.DurationField(blank=True, null=True)),
                ('stop_sequence', models.PositiveIntegerField()),
                ('stop_headsign', models.CharField(blank=True, max_length=255)),
                ('pickup_type', models.PositiveSmallIntegerField(choices=[(0, 'Regularly scheduled'), (1, 'Not available'), (2, 'Arrange by phone'), (3, 'Coordinate with driver')], default=0)),
                ('drop_off_type', models.PositiveSmallIntegerField(choices=[(0, 'Regularly scheduled'), (1, 'Not available'), (2, 'Arrange by phone'), (3, 'Coordinate with driver')], default=0)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_times', to='gtfs.stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_times', to='gtfs.trip')),
            ],
            options={
                'ordering': ('trip_id', 'stop_sequence'),
                'constraints': [models.UniqueConstraint(fields=('trip', 'stop_sequence'), name='gtfs_unique_trip_stop_sequence')],
            },
        ),
    ]
